### ISSUE TITLE
Should we consider deprecating deprecated methods in cdi-rs?

### ISSUE THREAD

**Issue by Apokleos** [cncf-tags/container-device-interface-rs#2]
As [cdi-go/registry.go](https://github.com/cncf-tags/container-device-interface/blob/main/pkg/cdi/registry.go) says that the methods starting with Registry*  are deprecated and will be removed in a future version.

Should we consider deprecating deprecated methods in cdi-rs?
cc @zvonkok

**Comment by zvonkok** [comment]
Yes we should definitely deprecate them. I started on this but haven't finished it yet. So please go on and adjust to the new API

**Comment by zvonkok** [comment]
This is done, closing
